title = "Workshop1"
languageCode = "en-us"
baseURL = "https://example.org"
theme = ["video", "learn"]
defaultContentLanguageInSubdir = false
defaultContentLanguage = "eng"

[Outputs]
  home = ["HTML", "RSS", "JSON"]

[Params]
  author = "Christian Kniep"
  description = "Workshop description"
  showVisitedLinks = true
  editURL = "https://github.com"

[languages]
