title = "My Workshop"
languageCode = "en-us"
baseURL = "https://example.org"
theme = "hugo-theme-learn"

[Outputs]
  home = ["HTML", "RSS", "JSON"]

[Params]
  author = "Christian Kniep"
  description = "My first workshop to test out the go redux script"
  showVisitedLinks = false
  editURL = "https://github.com"